CREATE DATABASE PPSII

CREATE TABLE Alumnos(
    Id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Apellido VARCHAR(100) NOT NULL,
    DNI VARCHAR(10) NOT NULL
)

DESCRIBE Alumnos;